name: htc
channels:
  - anaconda
  - pytorch
  - astra-toolbox
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - astra-toolbox=2.1.2
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - cloudpickle=2.0.0
  - cpuonly=2.0
  - cryptography=38.0.1
  - cudatoolkit=11.3.1
  - cytoolz=0.11.0
  - dask-core=2022.7.0
  - ffmpeg=4.3
  - fftw=3.3.9
  - freetype=2.12.1
  - fsspec=2022.7.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.19.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - jxrlib=1.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libaec=1.0.4
  - libastra=2.1.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.85.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - networkx=2.8.4
  - numpy=1.23.3
  - numpy-base=1.23.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - partd=1.2.0
  - pillow=9.2.0
  - pip=22.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.13
  - pytorch=1.13.0
  - pytorch-mutex=1.0
  - pywavelets=1.3.0
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - scikit-image=0.19.2
  - scipy=1.9.1
  - setuptools=65.5.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.39.3
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.11.2
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - typing_extensions=4.3.0
  - tzdata=2022e
  - urllib3=1.26.12
  - wheel=0.37.1
  - xz=5.2.6
  - yaml=0.2.5
  - zfp=0.5.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - future==0.18.2
    - h5py==3.7.0
    - https://github.com/odlgroup/odl/archive/master.zip
    - mat73
